version: "2"

services:
  amadeus-nginx:
    image: 630542070554.dkr.ecr.eu-central-1.amazonaws.com/flight/invia/service/amadeus/nginx:latest
    container_name: amadeus-nginx
    ports:
      - "80:80"
    volumes:
      - amadeus-php-sock:/sock

  amadeus-php:
    image: 630542070554.dkr.ecr.eu-central-1.amazonaws.com/flight/invia/service/amadeus/app:latest
    container_name: amadeus-php
    volumes:
      - amadeus-php-sock:/sock
    environment:
      CONFIG_CACHING: disabled
      MOCK_AMA_RESPONSE_IN_TEST: enabled

  redis:
    image: redis:3.2.10
    container_name: amadeus-redis

volumes:
  amadeus-php-sock:
