version: "3"

services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    container_name: service-amadeus-php
    volumes:
      - ./:/var/www

  nginx:
    image: nginx:latest
    container_name: service-amadeus-nginx
    volumes:
      - ./:/var/www
      - ./_docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./var/logs/nginx:/var/log/nginx
    ports:
      - "8201:80"
    depends_on:
      - php