version: "2"

services:
  amadeus-php:
    image: 630542070554.dkr.ecr.eu-central-1.amazonaws.com/flight/invia/service/amadeus/app:latest
    container_name: amadeus-php
    volumes:
      - ./:/var/www

  amadeus-nginx:
    image: 630542070554.dkr.ecr.eu-central-1.amazonaws.com/flight/invia/service/amadeus/nginx:latest
    container_name: amadeus-nginx
    volumes:
      - ./:/var/www
    ports:
      - "80:80"
