version: "2"

services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    container_name: service-amadeus-php
    volumes:
      - ./:/var/www
      - ./_docker/20-xdebug.ini:/etc/php/7.1/fpm/conf.d/20-xdebug.ini
      - ./var/logs/xdebug.log:/tmp/xdebug.log

  nginx:
    image: nginx:latest
    container_name: service-amadeus-nginx
    volumes:
      - ./:/var/www
      - ./_docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./var/logs/nginx:/var/log/nginx
    ports:
      - "8205:80"
    depends_on:
      - php
