#
# Services
#
apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}
  namespace: ${K8S_NAMESPACE}
  labels:
    app: ${APP_NAME}
    team: ${TEAM_NAME}
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: ${APP_NAME}
---

#
# Pod Disuption Budget
#
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: ${APP_NAME}
  namespace: ${K8S_NAMESPACE}
  labels:
    app: ${APP_NAME}
    team: ${TEAM_NAME}
spec:
  selector:
    matchLabels:
      app: ${APP_NAME}
  maxUnavailable: 1
---

#
# Horizontal Pod Autoscaler
#
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ${APP_NAME}
  namespace: ${K8S_NAMESPACE}
  labels:
    app: ${APP_NAME}
    team: ${TEAM_NAME}
spec:
  scaleTargetRef:
    kind: Deployment
    name: ${APP_NAME}
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
---

#
# Secrets
#
apiVersion: v1
kind: Secret
metadata:
  name: ${APP_NAME}
  namespace: ${K8S_NAMESPACE}
  labels:
    app: ${APP_NAME}
    team: ${TEAM_NAME}
type: Opaque
data:
  app.yml: ${APP_CONFIG}
---

#
# Deployments
#
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ${APP_NAME}
  namespace: ${K8S_NAMESPACE}
  labels:
    app: ${APP_NAME}
    team: ${TEAM_NAME}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 15%
      maxUnavailable: 0
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: ${APP_NAME}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
        team: ${TEAM_NAME}
        version: ${TAG}
    spec:
      imagePullSecrets:
        - name: ecr
      containers:
        - name: ${APP_NAME}-nginx
          image: ${REGISTRY}/flight/invia/service/amadeus/nginx:${TAG}
          ports:
            - name: http
              containerPort: 80
          resources:
            limits:
              cpu: 100m
              memory: 48Mi
            requests:
              cpu: 10m
              memory: 24Mi
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
          volumeMounts:
            - name: php-socket
              mountPath: /sock
        - name: ${APP_NAME}-php
          image: ${REGISTRY}/flight/invia/service/amadeus/app:${TAG}
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 192Mi
          volumeMounts:
            - name: app-config
              mountPath: /var/www/config
            - name: php-socket
              mountPath: /sock
      volumes:
        - name: app-config
          secret:
            secretName: ${APP_NAME}
        - name: php-socket
          emptyDir: {}
