## PHP charts override
php:
  serviceName: amadeus
  
  team: search-compare

  ## NGINX
  nginx:
    image:
      repository: flight/invia/service/amadeus/nginx

  ## Application
  app:
    image:
      repository: flight/invia/service/amadeus/app

    ## php application resource usage
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 192Mi

    readinessProbe:
      httpGet:
        path: /health

## Redis
redis:
  enabled: false
  usePassword: false
