search:
    wsdl: 1ASIWUFITBD_PDT_20180206_095616.wsdl

    allowed_types:
        - round-trip
        - one-way
        - open-jaw
    allowed_cabin_class:
        - Y
        - F
        - C

    flight_cache:
        adapter: void   # options are: void, apcu, file, memcached, redis (@see CacheProvider)
        life_time: 3600
        memcached:
            host: amadeus-memcache
            port: 11211
        redis:
            host: amadeus-redis
            port: 6379

    request_options:
        - "RW" # only if coopCodes are given
        - "RP"
        - "RU"
        - "ET"
        - "RDI" # include cross-border airports (e.g. EAP (MLH, BSL))
        - "PSB" # return best applicable fare, which does not need to split the pnr
        - "TAC"
        - "XLC" # To avoid ATLA (Amadeus Ticketless Access) carriers

    overnight_options: #copied from IbeConfig
        - "OVN"
        - "NVS"

    bag_option:
        - "BAG"

    coop_codes:      #copied from IbeConfigAbstract
        - "000867" # AER
        - "374186" # BA-NOBAG
        - "513058" # SN-NOBAG
        - "HBO01"  # AY-NOBAG

    area_search_distance: 100

    flexible_date_range: 2

    excluded_airlines:
        - "GA"
        - "JQ"
        - "3K"
        - "QS"
        - "9F"
        - "V7"
        - "Z6"
        - "GK"
        - "4Q"
        - "W3"
        - "GK"
        - "PK"
        - "NK"
        - "BL"

remarks:
    wsdl: 1ASIWUFITBD_PDT_20180206_095616.wsdl

response:
    json_encoding_options:
        - JSON_PRETTY_PRINT
        - JSON_UNESCAPED_SLASHES

debug:
    search:
      log_ama_traffic: true
    pimpledump:
        enabled: true
    remarks:
      log_ama_traffic: true
    pimpledump:
        enabled: true
    throwup:
        enabled: true

session:
    wsdl: 1ASIWADMTBD/1ASIWADMTBD_PDT_20180606_092050.wsdl

response:
    json_encoding_options:
        - JSON_PRETTY_PRINT
        - JSON_UNESCAPED_SLASHES

debug:
    search:
      log_ama_traffic: false
    pimpledump:
        enabled: true
    remarks:
      log_ama_traffic: false
    pimpledump:
        enabled: true
    throwup:
        enabled: true