FORMAT: 1A

# Amadeus Service

This service is the main communication operator to Amadeus. It shall handle any kind
of request concerning the GDS.

#### Search [POST /flight-search/]

This request will access the flight search endpoint of amadeus with mapped sent parameters
and business case configurations of the use-case, request an result and return it in the standardized
format.

+ Request

    + Body
        <!-- include(payload/request.json) -->
        

+ Response 200 (application/hal+json)

    This response resembles a default response of mapped itineraries as search result.

    + Body
    
        <!-- include(payload/response.json) -->
        
    + Schema
    
        <!-- include(payload/response-schema.json) -->

+ Response 500 (application/hal+json)

    This response represents an error response. The errors of this application can vary a lot depending of the
    the nature of the error, for example also amadeus response errors will be returned in that format, but maybe
    with a lot of missing information.

    |Code | Message | Hint |
    |---|---|---|
    | ARS0001 | The `Amadeus\Client::securityAuthenticate` method didn't return state OK | |
    | ARS0002 | The provided search parameters do not suffice the necessary data to start a new search | |
    | ARS0003 | The provided request could not be mapped into the appropriate format | Usually occurs when the request is not send in the right format |
    | ARS000X | *Every unspecific exception thrown by PHP will return such response if handled correctly, aswell as Amadeus response errors.* | |

    + Body
    
        <!-- include(payload/error.json) -->
        
## Healthcheck [/health/]

This endpoint will report main state of the service

### Healthcheck [POST]

+ Request
    + Headers
        
            Accept: text/plain
    
+ Response 200 (text/plain)
    
            I am alive.
### Healthcheck [GET]

+ Request
    + Headers
        
            Accept: text/plain
    
+ Response 200 (text/plain)
    
            I am alive.
